# Generated by Django 4.2.3 on 2023-07-31 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_profile_pic_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(choices=[('Shirts', 'Shirts'), ('Jeans', 'Jeans'), ('T-Shirts', 'T-Shirts'), ('Jackets', 'Jackets')], max_length=100)),
                ('product_brand', models.CharField(choices=[("Levi's", "Levi's"), ('Jack & Jones', 'Jack & Jones'), ('Zara', 'Zara'), ('Allen Solly', 'Allen Solly')], max_length=100)),
                ('product_size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.PositiveIntegerField()),
                ('product_pic', models.ImageField(upload_to='product_pic/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
